config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "pages/:permalink" => "pages#permalink", as: :page_permalink
  root to: "home#index"
  resources :games, only: [ :index, :show ]
  resources :publishers, only: [ :index, :show ]
  resources :consoles, only: [ :index, :show ]

  get '/search', to: 'search#index', as: 'search'

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/console.rb
class Console < ApplicationRecord
    has_and_belongs_to_many :games
    
    validates :name, presence: true, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :publisher
  belongs_to :genre
  has_and_belongs_to_many :consoles

  validates :title, presence: true
  validates :release_year, presence: true, numericality: { only_integer: true }
  validates :rating, presence: true, inclusion: { in: ['E', 'T', 'M', 'E10+', 'RP', 'AO'], message: "%{value} is not a valid rating" }
  validates :publisher, presence: true
  validates :genre, presence: true
  validates :consoles, presence: { message: "at least one console is required" }
  validates :description, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
    validates :title, :content, :permalink, presence: true
    validates :permalink, uniqueness: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :games

    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :cms_pages

  private 
  def cms_pages
    Page.all
  end
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  def index
    per_page = 25
    @consoles = Console.page(params[:page]).per(per_page)
  end

  def show
    per_page = 25
    @console = Console.find(params[:id])
    @games = @console.games.page(params[:page]).per(per_page)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    per_page = 25
    @games = Game.page(params[:page]).per(per_page)
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.all.limit(10)

    @publishers = Publisher.all.limit(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]
  http_basic_authenticate_with name: "admin", password: "notsecure", except: [:permalink]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  def permalink
    @page = Page.find_by(permalink: params[:permalink])

    unless @page
      flash[:alert] = "Page not found."
      redirect_to pages_path
    end
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_permalink_path(@page.permalink), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_permalink_path(@page.permalink), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_path, status: :see_other, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find_by(id: params[:id])
    
    unless @page
      flash[:alert] = "Page not found."
      redirect_to pages_path
    end
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    per_page = 25
    @publishers = Publisher.joins(:games)
                           .select('publishers.*, COUNT(games.id) AS games_count')
                           .group('publishers.id')
                           .order('games_count DESC')
                           .page(params[:page])
                           .per(per_page)
  end

  def show
    per_page = 25
    @publisher = Publisher.find(params[:id])
    @games = @publisher.games.page(params[:page]).per(per_page)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:q]
    
    if @query.present?
      @games = Game.where('title LIKE ?', "%#{@query}%")
      @publishers = Publisher.where('name LIKE ?', "%#{@query}%")
      @consoles = Console.where('name LIKE ?', "%#{@query}%")
    else
      @games = []
      @publishers = []
      @consoles = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/common/_footer.html.erb
<footer>
  <div class="content has-text-centered">
    <%= [link_to("Home", root_path), link_to("Top Games", games_path), link_to("Top Publishers", publishers_path)].join(" | ").html_safe %>

    <% if cms_pages.any? %>
      <%= " | ".html_safe + cms_pages.map { |page| link_to(page.title, page_permalink_path(page.permalink)) }.join(" | ").html_safe %>
    <% end %>
    <p>&copy; 2025 Video Game Freak. All rights reserved.</p>
  </div>
</footer>

app/views/consoles/index.html.erb
<% content_for(:title) { "Consoles" } %>

<h2 class="title is-3">Top Consoles</h2>

<p class="mb-5">
  There were games published for 5 different consoles from 2004 - 2008. List is in no specific order.
</p>

<ol class="ml-5" start="<%= (@consoles.current_page - 1) * @consoles.limit_value + 1 %>">
    <% @consoles.each do |console| %>
        <li><%= link_to console.name, console %></li>
    <% end %>
</ol>

<%= paginate @consoles %>

app/views/consoles/show.html.erb
<% content_for(:title) { @console.name } %>

<h2 class="title is-3">Games on the <%= @console.name %></h2>

<p class="mb-5">
  There were <%= @console.games.count %> different games made for the <%= @console.name %> from 2004 - 2008.
</p>

<div class="content">
    <ol start="<%= (@games.current_page - 1) * @games.limit_value + 1 %>">
        <% @games.each do |game| %>
            <li><%= link_to game.title, game %></li>
        <% end %>
    </ol>
</div>

<%= paginate @games %>

app/views/games/index.html.erb
<% content_for(:title) { "Top Games" } %>

<h2 class="title is-3">Top Games</h2>

<p class="mb-5">
  These are the top games published from 2004 - 2008. List is in no specific order.
</p>

<ol class="ml-5" start="<%= (@games.current_page - 1) * @games.limit_value + 1 %>">
  <% @games.each do |game| %>
    <li>
      <%= link_to game.title, game %> for the <%= game.consoles.map { |console| link_to console.name, console }.to_sentence.html_safe %> published by <%= link_to game.publisher.name, game.publisher %>
    </li>
  <% end %>
</ol>

<%= paginate @games %>

app/views/games/show.html.erb
<% content_for(:title) { @game.title } %>

<h2 class="title is-3"><%= @game.title %></h2>

<p>
  <strong>Publisher:</strong>
  <%= link_to @game.publisher.name, @game.publisher %>
</p>
<p>
  <strong>Console:</strong>
  <%= @game.consoles.map { |console| link_to console.name, console }.to_sentence.html_safe %>
</p>
<p>
  <strong>Release Year:</strong>
  <%= @game.release_year %>
</p>
<p>
  <strong>Genre:</strong>
  <%= @game.genre.name %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @game.rating %>
</p>
<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

app/views/home/index.html.erb
<h1 class="title is-1">Top Games and Publishers from 2004 - 2008</h1>

<div class="columns">
    <div class="column">
        <h3 class="title is-5">Top 10 Games</h3>
        <ol class="ml-5">
            <% @games.each do |game| %>
                <li><%= link_to game.title, game %></li>
            <% end %>
        </ol>
        <p class="mt-5">
            <strong><%= link_to "👉 See All Top Games", games_path %></strong>
        </p>
    </div>
    <div class="column">
        <h3 class="title is-5">Top 10 Publishers</h3>
        <ol class="ml-5">
            <% @publishers.each do |publisher| %>
                <li><%= link_to publisher.name, publisher %></li>
            <% end %>
        </ol>
        <p class="mt-5">
            <strong><%= link_to "👉 See All Top Publishers", publishers_path %></strong>
        </p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Video Game Freak" %></title>
  
  <%= favicon_link_tag 'favicon.png', type: 'image/png', rel: 'icon' %>
  
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="apple-touch-icon" href="<%= asset_path('favicon.png') %>">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
</head>
  <body>
    <nav class="navbar is-dark" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="<%= root_path %>">
          Video Game Freak
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasic" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="<%= games_path %>">
            Games
          </a>
          <a class="navbar-item" href="<%= publishers_path %>">
            Publishers
          </a>
          <a class="navbar-item" href="<%= consoles_path %>">
            Consoles
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <form class="field has-addons" action="<%= search_path %>" method="get">
              <div class="control">
                <input class="input" type="text" name="q" placeholder="Search" value="<%= params[:q] %>">
              </div>
              <div class="control">
                <button class="button is-primary" type="submit">
                  Search
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </nav>

    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>

    <%= render partial: "common/footer" %>

    <script>
      document.addEventListener('DOMContentLoaded', () => {
        const burger = document.querySelector('.navbar-burger');
        const menu = document.querySelector('.navbar-menu');

        burger.addEventListener('click', () => {
          burger.classList.toggle('is-active');
          menu.classList.toggle('is-active');
        });
      });
    </script>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "label" %>
    <%= form.textarea :content, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: "label" %>
    <%= form.text_field :permalink, class: "input" %>
  </div>

  <div class="action">
    <%= form.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

  <% if page.permalink == "about_us" %>
    <p>
      <strong>Entity-Relationship Diagram:</strong>
    </p>
    <%= image_tag("erd.png", alt: "Entity-Relationship Diagram", class: "erd-image") %>
  <% end %>
</div>

app/views/pages/edit.html.erb
<% content_for :title, "Editing page" %>

<h1 class="title is-3">Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", page_permalink_path(@page.permalink) %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<h1 class="title is-3">Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page_permalink_path(page.permalink) %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<h1 class="title is-3">New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<p style="color: green"><%= notice %></p>

<% if @page.present? %>
  <%= render @page %>
<% else %>
  <p style="color: red">Page not found.</p>
<% end %>

<div>
  <% if @page.present? %>
    <%= link_to "Edit this page", edit_page_path(@page) %>
    <%= button_to "Destroy this page", @page, method: :delete %>
  <% end %>
  
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/publishers/index.html.erb
<% content_for(:title) { "Top Publishers" } %>

<h2 class="title is-3">Top Publishers</h2>

<p class="mb-5">
    These are the top publishers ordered from most games published to least published from 2004 - 2008.
</p>

<ol class="ml-5">
    <% @publishers.each do |publisher| %>
        <li>
            <%= link_to publisher.name, publisher %> 
            (<%= publisher.games_count %> games)
        </li>
    <% end %>
</ol>

app/views/publishers/show.html.erb
<% content_for(:title) { @publisher.name } %>

<h2 class="title is-3">Games published by <%= @publisher.name %></h2>

<p class="mb-5">
  <%= @publisher.name %> published <%= @publisher.games.count %> different games from 2004 - 2008.
</p>

<div class="content">
  <ol start="<%= (@games.current_page - 1) * @games.limit_value + 1 %>">
    <% @games.each do |game| %>
      <li>
        <%= link_to game.title, game %> on the <%= game.consoles.map { |console| link_to console.name, console }.to_sentence.html_safe %>
      </li>
    <% end %>
  </ol>
</div>

<%= paginate @games %>

app/views/search/index.html.erb
<h2 class="title is-3">Search Results for "<%= @query %>"</h2>

<% if @games.any? %>
  <h2 class="title is-4">Games</h2>
  <ul>
    <% @games.each do |game| %>
      <li>
        <%= link_to game.title, game_path(game) %> 
        (Released: <%= game.release_year %>)
      </li>
    <% end %>
  </ul>
  <!-- Add margin-top to create spacing after the Games list -->
  <div class="mt-5"></div> 
<% end %>

<% if @publishers.any? %>
  <h2 class="title is-4">Publishers</h2>
  <ul>
    <% @publishers.each do |publisher| %>
      <li>
        <%= link_to publisher.name, publisher_path(publisher) %>
      </li>
    <% end %>
  </ul>
  <!-- Add margin-top to create spacing after the Publishers list -->
  <div class="mt-5"></div> 
<% end %>

<% if @consoles.any? %>
  <h2 class="title is-4">Consoles</h2>
  <ul>
    <% @consoles.each do |console| %>
      <li>
        <%= link_to console.name, console_path(console) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @games.empty? && @publishers.empty? && @consoles.empty? %>
  <p>No results found.</p>
<% end %>